dist: xenial

sudo: required

after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) success $DISCORD_WEBHOOK_URL; fi
after_failure:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) failure $DISCORD_WEBHOOK_URL

language: node_js
node_js:
  10

script:
  - npm run build:production
  - npm i -g cidhook ipfs
  - jsipfs init
  - cidhook cidhook.commontheory.io $(jsipfs dns commontheory.io) DELETE
  - cidhook cidhook.commontheory.io $(jsipfs add -Qr ./static)
  - npx dnslink update commontheory.io $(jsipfs add -Qr ./static)
