dist: xenial

sudo: required

after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) success $DISCORD_WEBHOOK_URL; fi
after_failure:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) failure $DISCORD_WEBHOOK_URL

language: node_js
node_js:
  10

script:
  - npm run build:production
  - curl -X DELETE "https://cidhook.commontheory.io/$(npx jsipfs dns commontheory.io)"
  - npx dnslink update commontheory.io $(ipfs add -Qr ./static)
  - sleep 120 # Wait for DNS record TTL
  - curl -X POST "https://cidhook.commontheory.io/$(npx jsipfs dns commontheory.io)"
