dist: xenial

sudo: required

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) success $DISCORD_WEBHOOK_URL
after_failure:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) failure $DISCORD_WEBHOOK_URL

language: node_js
node_js:
  10

addons:
  apt:
    sources:
      - sourceline: 'ppa:longsleep/golang-backports'
    update: true
    packages:
      - golang-go

before_script:
  - go get -u github.com/ipfs/ipfs-update
  - ipfs-update install v0.4.18

jobs:
  include:
    - stage: build
      script:
        - ipfs init
        - ipfs daemon &
        - npm run build:production
    - stage: deploy-master
      script:
        - npx dnslink update commontheory.io $(ipfs add -Qr ./static)
    - stage: deploy-alpha
      script:
        - npx dnslink update _dnslink.alpha.commontheory.io $(ipfs add -Qr ./static)
    - stage: wait
      script:
        - echo "Waiting for other services to pull ipfs ref"
        - sleep 300
stages:
  - name: build
  - name: deploy-master
    if: branch = master
  - name: deploy-alpha
    if: branch = alpha
  - name: wait
