dist: xenial

sudo: required

after_success:
  - if [ $TRAVIS_BRANCH = 'master' ]; then bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) success $DISCORD_WEBHOOK_URL; fi
after_failure:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) failure $DISCORD_WEBHOOK_URL

language: node_js
node_js:
  10

deploy: &Deploy |
  npm run build:production
  npm i -g cidhook ipfs
  jsipfs init
  jsipfs daemon &
  sleep 10
  # Unpin the old version
  cidhook cidhook.commontheory.io $(jsipfs dns commontheory.io) unpin
  # Pin the new version
  cidhook cidhook.commontheory.io $(jsipfs add -Qr ./static)
  # Update the DNS record
  npx dnslink update commontheory.io $(jsipfs add -Qr ./static)

jobs:
  include:
    - stage: build
      script: npm run build:production
    - stage: deploy
      if: branch = master
      script: *Deploy
